### ISSUE TITLE
npm install hipack fails on windows

### ISSUE THREAD

**Issue by ryan-morris** [rauls/nodejs-pack#4]
using windows 8 64 bit and visual studio 2013. Python 2.7.

C:\Source\myProj2\node_modules\hipack>node "C:\Program Files\nodejs\node_modul
es\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild
child_process: customFds option is deprecated, use stdio instead.
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  pack.cc
..\pack.cc(14): fatal error C1083: Cannot open include file: 'sys/param.h': No
such file or directory [C:\Source\myProj2\node_modules\hipack\build\hipack.vc
xproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067
:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modu
les\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Source\myProj2\node_modules\hipack
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs
\node_modules\npm\bin\npm-cli.js" "install" "--save" "hipack" "-msvs_version
=2013"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! hipack@1.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hipack@1.0.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the hipack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls hipack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Source\myProj2\npm-debug.log

**Comment by sce9sc** [comment]
Same issue here

node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  pack.cc
..\pack.cc(14): fatal error C1083: Cannot open include file: 'sys/param.h': No such file or directory [C:\Users\s.charitakis\Documents\Visual Studio 2013\Projects\minimob-vnext\trunk\offervault\Minimob.ST4.node.controller\node_modules\hipack\build\hipack.vcxpr
oj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\s.charitakis\Documents\Visual Studio 2013\Projects\minimob-vnext\trunk\offervault\Minimob.ST4.node.controller\node_modules\hipack
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok
npm ERR! hipack@1.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hipack@1.0.4 install script.
npm ERR! This is most likely a problem with the hipack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls hipack
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "hipack"
npm ERR! cwd C:\Users\s.charitakis\Documents\Visual Studio 2013\Projects\minimob-vnext\trunk\offervault\Minimob.ST4.node.controller
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\s.charitakis\Documents\Visual Studio 2013\Projects\minimob-vnext\trunk\offervault\Minimob.ST4.node.controller\npm-debug.log
npm ERR! not ok code 0

**Comment by carlitose** [comment]
Same issue, but with Mac OS X.

**Comment by mrpetef10** [comment]
Same Issue with windows 8 64Bit

**Comment by mostend** [comment]
Same Issue with windows 10 64Bit
