### ISSUE TITLE
install fail on windows 10 64 : Cannot open include file: 'sys/param.h'

### ISSUE THREAD

**Issue by philmon4** [rauls/nodejs-pack#8]
npm-v = 4.1.2
node -v = v7.7.3

npm instal hipack

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  pack.cc
  win_delay_load_hook.cc
..\pack.cc(14): fatal error C1083: Cannot open include file: 'sys/param.h': No such file or directory [D:\PROG\node\linkTest\node_modules\hipack\build\h
ipack.vcxproj]

gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\pm\nvm\v7.7.3\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\pm\\nvm\\v7.7.3\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\PROG\node\linkTest\node_modules\hipack
gyp ERR! node -v v7.7.3
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
npm WARN linktest@1.0.0 No description
npm WARN linktest@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "hipack"
npm ERR! node v7.7.3
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! hipack@1.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1

**Comment by nanomo** [comment]
same here
node -v
v8.12.0

npm -v
6.4.1

**Comment by Natas0007** [comment]
Anyone ever get this one figured out?  I'm having the exact same issue.  Node v12.18.3.  Thx!
